accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accountapp.views import AccountDetailView, AccountCreateView, AccountUpdateView, AccountDeleteView

app_name = "accountapp"

urlpatterns = [
    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('create/', AccountCreateView.as_view(), name='create'),
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),
]

articleapp/urls.py
from django.urls import path
from django.views.generic import TemplateView

from articleapp.views import ArticleCreateView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView, ArticleListView

app_name = 'articleapp'
urlpatterns =[
    path('list/', ArticleListView.as_view(template_name='articleapp/list.html'), name='list'),
    path('create/', ArticleCreateView.as_view(), name='create'),
    path('detail/<int:pk>', ArticleDetailView.as_view(), name='detail'),
    path('update/<int:pk>', ArticleUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', ArticleDeleteView.as_view(), name='delete'),
    path('articles/list/<str:category_name>/', ArticleListView.as_view(), name='list'),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from articleapp.views import ArticleListView

urlpatterns = [
    path('', ArticleListView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls')),
    path('projects/', include('projectapp.urls')),
    path('subscribe/', include('subscribeapp.urls')),
    path('likes/', include('likeapp.urls')),
    path('accounts/', include('allauth.urls')),
    path('plus/', include('plusdefapp.urls')),
    path('chatgptcode/', include('chatgptcodeapp.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('jjit/', include('jjit.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

jjit/urls.py
#awesite/jjit/urls.py

from django.urls import path
from . import views

app_name = 'jjit' # 앱 이름 정의

urlpatterns = [
    path('', views.index, name='index'), # 'index'라는 이름으로 URL 패턴에 이름 부여
    path('<int:question_id>/', views.detail, name='detail'), # 'detail'이라는 이름으로 URL 패턴에 이름 부여
    path('<int:question_id>/answer/create/', views.answer_create, name='answer_create'),
    path('question/create/', views.question_create, name='question_create'),#질문 추가 버튼
    path('question/modify/<int:question_id>/', views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', views.question_delete, name='question_delete'),
    path('answer/modify/<int:answer_id>/', views.answer_modify, name='answer_modify'),


    # 'answer_create'라는 이름으로 URL 패턴에 이름 부여,#93
]

likeapp/urls.py
from django.urls import path

from likeapp.views import LikeArticleView

app_name='likeapp'

urlpatterns = [
    path('article/like/<int:pk>', LikeArticleView.as_view(), name='article_like'),
]

profileapp/urls.py
from django.urls import path

from profileapp.views import ProfileCreateView, ProfileUpdateView

app_name = 'profileapp'
urlpatterns = [
    path('create/', ProfileCreateView.as_view(), name='create'),
    path('update/<int:pk>', ProfileUpdateView.as_view(), name='update'),
]

projectapp/urls.py
from django.urls import path

from projectapp.views import ProjectCreateView, ProjectDetailView, ProjectListView

app_name = 'projectapp'

urlpatterns = [
    path('list/',ProjectListView.as_view(), name='list'),
    path('create/', ProjectCreateView.as_view(), name='create'),
    path('detail/<int:pk>', ProjectDetailView.as_view(), name='detail'),

]

accountapp/models.py
from django.db import models


# Create your models here.

accountapp/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User


class AccountUpdateForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # 회원정보수정 중 아이디 비활성화
        self.fields['username'].disabled = True

accountapp/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView
from django.views.generic.list import MultipleObjectMixin
from django.views.generic import DetailView
from subscribeapp.models import Subscription
from accountapp.decorators import account_ownership_required
from accountapp.forms import AccountUpdateForm
from articleapp.models import Article




has_ownership = [login_required, account_ownership_required]


# Create your views here.


class AccountCreateView(CreateView):
    # 장고에서 제공하는 기본 모델
    model = User
    form_class = UserCreationForm
    success_url = reverse_lazy('accountapp:login')
    # reverse_lazy는 클래스에서
    template_name = 'accountapp/create.html'
    # 어느 html파일로 갈지




class AccountDetailView(DetailView, MultipleObjectMixin):
    model = User
    context_object_name = 'target_user'
    template_name = 'accountapp/detail.html'
    paginate_by = 20

    def get_context_data(self, **kwargs):
        object_list = Article.objects.filter(writer=self.get_object())

        subscription_list = Subscription.objects.filter(user=self.get_object())
        projects = subscription_list.values_list('project', flat=True)
        subscription_articles = Article.objects.filter(project__in=projects)

        context = super().get_context_data(object_list=object_list, **kwargs)
        context['subscription_list'] = subscription_list
        context['subscription_articles'] = subscription_articles
        return context



@method_decorator(has_ownership, 'get')
@method_decorator(has_ownership, 'post')
class AccountUpdateView(UpdateView):
    # 장고에서 제공하는 기본 모델
    model = User
    context_object_name = 'target_user'
    # 장고에서 제공하는 html
    form_class = AccountUpdateForm
    success_url = reverse_lazy('accountapp:login')
    # reverse_lazy는 클래스에서
    template_name = 'accountapp/update.html'

    # 어느 html파일로 갈지


@method_decorator(has_ownership, 'get')
@method_decorator(has_ownership, 'post')
class AccountDeleteView(DeleteView):
    model = User
    context_object_name = 'target_user'
    success_url = reverse_lazy('accountapp:login')
    template_name = 'accountapp/delete.html'

    '''def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.object = None

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        # 자바스크립트 confirm 메시지를 띄우고 확인 버튼을 누르면 삭제 수행
        confirm_message = "회원탈퇴를 진행하시겠습니까?"
        if request.POST.get('confirm_message') == confirm_message:
            self.object.delete()
            return HttpResponse("회원탈퇴가 완료되었습니다.")
        else:
            return render(request, self.template_name, {'target_user': self.object})'''

accountapp/templates/accountapp/create.html
{% extends 'base.html' %}

{% block content %}
    <div class="study_description"
         style="padding-bottom: 20px">
        <h1>Join to Service</h1>
    </div>
  <div class="container mt-5">
    <div class="row justify-content-center">
      <div class="col-md-6"style="width: 100%">
        <div class="card shadow-sm"
             style="background-color: rgb(17 24 39);
                    width: 100%;
                    border: 0px;
                    border-radius: 0%;"
        >
          <div class="card-body" style="background-color: rgb(31 41 55); width: 300px">
            <form action="{% url 'accountapp:create' %}" method="POST" onsubmit="return validateForm()">
              {% csrf_token %}
              <div class="form-group" style="width: 260px">
                <label for="username" style="color: rgb(156, 163, 175)">ID</label>
                <input type="text" name="username" id="username" class="form-control" placeholder="아이디를 입력하세요">
              </div>
              <div class="form-group" style="margin-top:1rem">
                <label for="password1" style="color: rgb(156, 163, 175)">Password</label>
                <input type="password" name="password1" id="password1" class="form-control" placeholder="비밀번호를 입력하세요">
              </div>
              <div class="form-group" style="margin-top:1rem">
                <label for="password2" style="color: rgb(156, 163, 175)">Comfirm password</label>
                <input type="password" name="password2" id="password2" class="form-control" placeholder="비밀번호를 다시 입력하세요">
              </div>
              <div class="text-center">
                <button class="btn btn-primary mx-auto"
                        style="margin-top:2rem;
                               background-color: antiquewhite;
                               color: black;
                               font-family: inherit;
                               font-weight: 800;
                               font-size: .875rem;"
                >Create Account
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>


  <script>
    function validateForm() {
      var username = document.getElementById("username").value;
      var password1 = document.getElementById("password1").value;
      var password2 = document.getElementById("password2").value;
      var password2Label = document.querySelector('label[for="password2"]');

      if (username == "") {
        alert("아이디를 입력하세요");
        return false;
      }
      if (password1 == "") {
        alert("비밀번호를 입력하세요");
        return false;
      }
      if (password2 == "") {
        alert("비밀번호 확인을 입력하세요");
        return false;
      }
      if (password1 !== password2) {
        password2Label.innerHTML += ' <span style="color:red;">(입력하신 비밀번호와 다릅니다)</span>';
        return false;
      }
      return true;
    }
  </script>
{% endblock %}

accountapp/templates/accountapp/delete.html
{% extends 'base.html' %}
{% block content %}
    <div style="text-align: center; max-width: 500px; margin: 4rem auto;">
       <div class="mb-4">
           <h2>회원 탈퇴</h2>
       </div>
        <form action ="{% url 'accountapp:delete' pk=target_user.pk %}" method="POST" id="delete-form" >
            {% csrf_token %}
            <input type="hidden" name="confirm_message" value="">
            <input type="submit" class="btn btn-danger col-4 mt-3" value="회원 탈퇴" onclick="return confirmDelete()">
        </form>
    </div>

    <script>
        function confirmDelete() {
            var message = "회원탈퇴를 진행하시겠습니까?";
            if (confirm(message)) {
                document.getElementById("delete-form").elements.namedItem("confirm_message").value = message;
                return true;
            } else {
                return false;
            }
        }
    </script>
{% endblock %}

accountapp/templates/accountapp/detail.html
<!-- detail.html -->
{% extends 'base.html' %}
{% block content %}
    <div>
        <div style="text-align: center; max-width: 500px; margin: 4rem auto;">
            <p>
                {{ target_user.date_joined }}
            </p>

            <!-- 유저가 프로필이 있다면 -->
            {% if target_user.profile %}
                <img style="height:8rem; width:8rem; border-radius: 50px; margin-bottom: 2rem; object-fit: cover"
                     src="{{ target_user.profile.image.url }}" alt="">
                <h2>
                    {{ target_user.profile.nickname }}
                    {% if target_user == user %}
                        <a class="material-icons"
                           style="box-shadow: 0 0 4px #ccc; border-radius:10rem; padding: .4rem;"
                           href="{% url 'profileapp:update' pk=target_user.profile.pk %}">
                            edit
                        </a>
                    {% endif %}
                </h2>
                <h4 style="margin: 2rem">
                    {{ target_user.profile.message }}
                </h4>
            {% else %}
                {% if target_user == user %}
                    <a href="{% url 'profileapp:create' %}">
                        <h2>
                            create Profile
                        </h2>
                    </a>
                {% else %}
                    <h2>
                        프로필 없음
                    </h2>
                {% endif %}
            {% endif %}

            <!-- 유저가 접속에 성공하면, 회원정보수정 및 회원탈퇴 보여주기 -->
            {% if target_user == user %}
                <a class="material-icons"
                   style="box-shadow: 0 0 4px #ccc; border-radius:10rem; padding: .4rem;"
                   href="{% url 'accountapp:update' pk=user.pk %}">
                    settings
                </a>

                <a class="material-icons"
                   style="box-shadow: 0 0 4px red; border-radius:10rem; padding: .4rem;"
                   href="{% url 'accountapp:delete' pk=user.pk %}">
                    cancel
                </a>
            {% endif %}
        </div>
    </div>
    <hr>
<h3>내가 쓴 글</h3>
    <div class="container">
        <div class="row row-cols-1 row-cols-md-3 g-4">
            {% for article in object_list|slice:":12" %}
                <!-- object_list를 12개로 제한 -->
                <div class="col">
                    <div class="card shadow">
                        <a href="{% url 'articleapp:detail' pk=article.pk %}">
                            <div class="card-body">
                                <h5 class="card-title">{{ article.title }}</h5>
                                <div class="d-flex align-items-center">
                                    <a href="{% url 'likeapp:article_like' pk=article.pk %}">
                                        <i class="material-icons {% if article.like > 0 %}text-danger{% endif %}"
                                           style="color: {% if article.like == 0 %}var(--color-black);{% else %}var(--color-pink);{% endif %}">
                                            favorite
                                        </i>
                                    </a>
                                    <span class="ms-1">{{ article.like }}</span>
                                </div>
                                <div class="card-text">
                                    <div class="mb-2">{{ article.writer.profile.nickname }}</div>
                                    <h6 class="hits">🖱조회수: {{ article.hits }}</h6>
                                    <div>{{ article.created_at }}</div>
                                </div>
                                <img src="{{ article.project.image.url }}" class="project-image" alt="">
                            </div>
                        </a>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

    <hr>

<!-- 수정된 코드 -->
<h3>구독</h3>
<ul>
    {% for subscription_article in subscription_articles %}
        <li>
            <a href="{% url 'projectapp:detail' pk=subscription_article.project.pk %}">
                <img src="{{ subscription_article.project.image.url }}" class="project2-image" alt="">
            </a>
        </li>
    {% endfor %}
</ul>



 <style>
        .circle-card {
            width: 100px;
            height: 100px;
            border-radius: 50%;
            overflow: hidden;
        }

        .circle-img-wrapper {
            width: 100%;
            height: 100%;
            display: flex;
            justify-content: center;
            align-items: center;
        }

        .project-image {
            width: 20px;
            height: 20px;
        }

        .project2-image {
            width: 100px;
            height: 100px;
        }
    </style>
{% endblock %}

accountapp/templates/accountapp/index.html
{% extends 'base.html' %}

<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <div>
            <h1>자기PR</h1>
    </div>
</body>

accountapp/templates/accountapp/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load socialaccount %}  <!-- socialaccount 태그 라이브러리 로드 -->
{% providers_media_js %}  <!-- socialaccount 미디어 JavaScript 파일 포함 -->

{% block content %}
    <div style="max-width: 500px; margin: 4rem auto;">
        <div>
            <h2 style="text-align: center; font-weight: 800;">Log in to Service</h2>
        </div>
        <div style="margin-top: 32px">
            <form style="justify-items: center" action="" method="POST" name="loginForm">
                {% csrf_token %}
                <div style="background-color: rgb(31 41 55);
                            padding: 32px 40px;
                            border: 5px solid rgb(31 41 55);
                            border-radius: 5%"
                     class="login_input">

                    <div class="form_group">
                        <label style="color: rgb(156, 163, 175)" for="id_username">ID</label>
                        <input type="text" name="username" id="id_username" class="form-control" placeholder="아이디를 입력하세요">
                    </div>

                    <div class="form-group" style="margin-top:1rem">
                        <label style="color: rgb(156, 163, 175)" for="id_password">PassWord</label>
                        <input type="password" name="password" id="id_password" class="form-control" placeholder="비밀번호를 입력하세요">
                    </div>

                    <div style="margin-top: 20px;" class="text-center">
                        <input type="submit"
                               style="background-color: white;
                                      color: black;
                                      font-family: inherit;
                                      font-weight: 800;
                                      font-size: .875rem;"
                               class="btn btn-success rounded-pill col-4 mt-3"
                               onclick="return validateForm();"
                               value="Continue →"
                        >
                    </div>
                </div>

                <div style="display: flex;">
                    <div style="content:'';
                                width: 230px;
                                border-bottom: 2px solid rgb(156 163 175);"
                    >
                    </div>
                    <span style="margin-left: 1.25rem;
                                margin-right: 1.25rem;
                                margin-top: 1.25rem;"
                    >
                        OR
                    </span>
                    <div style="content:'';
                                width: 230px;
                                border-bottom: 2px solid rgb(156 163 175);"
                    >
                    </div>
                </div>

                <div style="margin-top: 20px;" class="text-center">
                    <a href="{% provider_login_url 'google' %}" class="btn btn-success rounded-pill mt-3" style="background-color: rgb(66, 133, 244); color: black; font-family: inherit; font-weight: 800; font-size: 0.875rem;">
                        <i class="fa-solid fa-comment"></i>
                        Google login →
                    </a>
                </div>
            </form>
        </div>
    </div>

    <script>
        function validateForm() {
            const username = document.forms["loginForm"]["username"].value;
            const password = document.forms["loginForm"]["password"].value;
            if (username == "") {
                alert("아이디를 입력하세요");
                return false;
            }
            if (password == "") {
                alert("비밀번호를 입력하세요");
                return false;
            }
        }
    </script>
{% endblock %}

accountapp/templates/accountapp/update.html
{% extends 'base.html' %}
{% block content %}

<div style="max-width: 500px; margin: 4rem auto;">
    <div class="mb-4">
        <h2 style="text-align: center">회원정보수정</h2>
    </div>
    <form action="{% url 'accountapp:update' pk=target_user.pk %}" method="POST" onsubmit="return validateForm()">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_username">아이디</label>
            <input type="text" class="form-control" id="id_username" value="{{ target_user.username }}" disabled>
        </div>
        <div class="form-group" style="margin-top:1rem">
            <label for="id_password1">비밀번호</label>
            <input type="password" class="form-control" id="id_password1" name="password1" placeholder="비밀번호">
        </div>
        <div class="form-group" style="margin-top:1rem">
            <label for="id_password2">비밀번호 확인</label>
            <input type="password" class="form-control" id="id_password2" name="password2" placeholder="비밀번호 확인">
        </div>
        <div class="form-group text-center">
            <input type="submit" class="btn btn-primary col-4 mt-3" value="수정">
        </div>
    </form>
</div>
<script>
    function validateForm() {
        const password1 = document.querySelector('#id_password1').value;
        const password2 = document.querySelector('#id_password2').value;

        if (password1.trim() === '') {
            alert('비밀번호를 입력하세요');
            return false;
        }

        return true;
    }

    document.querySelector('form').addEventListener('submit', function(event) {
        const password1 = document.querySelector('#id_password1').value;
        const password2 = document.querySelector('#id_password2');

        if (password1 !== password2.value) {
            password2.insertAdjacentHTML('afterend', ' <span style="color:red;">(입력하신 비밀번호와 다릅니다)</span>');
            event.preventDefault();
        }

    });
</script>
{% endblock %}