accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accountapp.views import AccountDetailView, AccountCreateView, AccountUpdateView, AccountDeleteView

app_name = "accountapp"

urlpatterns = [
    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('create/', AccountCreateView.as_view(), name='create'),
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),
]

articleapp/urls.py
from django.urls import path
from django.views.generic import TemplateView

from articleapp.views import ArticleCreateView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView, ArticleListView

app_name = 'articleapp'
urlpatterns =[
    path('list/', ArticleListView.as_view(template_name='articleapp/list.html'), name='list'),
    path('create/', ArticleCreateView.as_view(), name='create'),
    path('detail/<int:pk>', ArticleDetailView.as_view(), name='detail'),
    path('update/<int:pk>', ArticleUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', ArticleDeleteView.as_view(), name='delete'),
    path('articles/list/<str:category_name>/', ArticleListView.as_view(), name='list'),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from articleapp.views import ArticleListView

urlpatterns = [
    path('', ArticleListView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls')),
    path('projects/', include('projectapp.urls')),
    path('subscribe/', include('subscribeapp.urls')),
    path('likes/', include('likeapp.urls')),
    path('accounts/', include('allauth.urls')),
    path('plus/', include('plusdefapp.urls')),
    path('chatgptcode/', include('chatgptcodeapp.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('jjit/', include('jjit.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

jjit/urls.py
#awesite/jjit/urls.py

from django.urls import path
from . import views

app_name = 'jjit' # 앱 이름 정의

urlpatterns = [
    path('', views.index, name='index'), # 'index'라는 이름으로 URL 패턴에 이름 부여
    path('<int:question_id>/', views.detail, name='detail'), # 'detail'이라는 이름으로 URL 패턴에 이름 부여
    path('<int:question_id>/answer/create/', views.answer_create, name='answer_create'),
    path('question/create/', views.question_create, name='question_create'),#질문 추가 버튼
    path('question/modify/<int:question_id>/', views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', views.question_delete, name='question_delete'),
    path('answer/modify/<int:answer_id>/', views.answer_modify, name='answer_modify'),


    # 'answer_create'라는 이름으로 URL 패턴에 이름 부여,#93
]

likeapp/urls.py
from django.urls import path

from likeapp.views import LikeArticleView

app_name='likeapp'

urlpatterns = [
    path('article/like/<int:pk>', LikeArticleView.as_view(), name='article_like'),
]

projectapp/urls.py
from django.urls import path

from projectapp.views import ProjectCreateView, ProjectDetailView, ProjectListView

app_name = 'projectapp'

urlpatterns = [
    path('list/',ProjectListView.as_view(), name='list'),
    path('create/', ProjectCreateView.as_view(), name='create'),
    path('detail/<int:pk>', ProjectDetailView.as_view(), name='detail'),

]

subscribeapp/urls.py
from django.urls import path

from subscribeapp.views import SubscriptionView, SubscriptionListView

app_name = 'subscribeapp'

urlpatterns = [
    path('subscribe/', SubscriptionView.as_view(), name='subscribe'),
    path('list/', SubscriptionListView.as_view(), name='list'),
]

projectapp/models.py
from django.db import models


# Create your models here.
class Project(models.Model):
    title = models.CharField(max_length=20, null=False)
    image = models.ImageField(upload_to='project/', null=False)
    description = models.CharField(max_length=200, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.pk} : {self.title}'


from django.db import models
# models.py

class SOUP(models.Model):
    title = models.CharField(max_length=100)
    content = models.CharField(max_length=1000)

    def __str__(self):
        return self.title


class IFREN(models.Model):
    title = models.CharField(max_length=100)
    content = models.CharField(max_length=1000)

    def __str__(self):
        return self.title
        return self.project_name

projectapp/forms.py
from django.forms import ModelForm

from projectapp.models import Project


class ProjectCreationForm(ModelForm):
    class Meta:
        model = Project
        fields = ['title', 'image', 'description']

projectapp/views.py
from django.shortcuts import render
from django.urls import reverse
from django.views.generic import CreateView, ListView, DetailView

from articleapp.models import Article
from projectapp.forms import ProjectCreationForm
from projectapp.models import Project
from subscribeapp.models import Subscription

import requests
from bs4 import BeautifulSoup

class ProjectCreateView(CreateView):
    model = Project
    form_class = ProjectCreationForm
    template_name = 'projectapp/create.html'

    def get_success_url(self):
        return reverse('projectapp:detail', kwargs={'pk': self.object.pk})


class ProjectDetailView(DetailView):
    model = Project
    context_object_name = 'target_project'
    template_name = 'projectapp/detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        project = self.object
        if user.is_authenticated:
            subscription = Subscription.objects.filter(user=user, project=project)
        else:
            subscription = None
        context['subscription'] = subscription

        # Get the list of articles related to the project
        article_list = Article.objects.filter(project=project)
        context['article_list'] = article_list

        # Crawl data from external sources
        inflearn_posts, soup_posts = crawl_inflearn_soup(project.title)
        context['inflearn_posts'] = inflearn_posts
        context['soup_posts'] = soup_posts

        return context


class ProjectListView(ListView):
    model = Project
    context_object_name = 'project_list'
    template_name = 'projectapp/list.html'
    paginate_by = 20

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Get the list of articles
        article_list = Article.objects.all()
        context['article_list'] = article_list

        return context


def crawl_inflearn_soup(title):
    inflearn_url = f'https://www.inflearn.com/community/studies?status=unrecruited&tag={title}&order=recent'
    soup_url = 'https://soup.pw/projects'

    inflearn_response = requests.get(inflearn_url)
    soup_response = requests.get(soup_url)

    if inflearn_response.status_code == 200 and soup_response.status_code == 200:
        inflearn_soup = BeautifulSoup(inflearn_response.content, 'html.parser')
        soup_soup = BeautifulSoup(soup_response.content, 'html.parser')

        inflearn_posts = []
        e_click_posts = inflearn_soup.find_all(class_='e-click-post')
        for post in e_click_posts[:5]:
            title = post.find(class_='title__text').get_text()
            body = post.find(class_='question__body').get_text()[:30] + "..."
            if "[개발 스터디 모집 내용 예시]" not in title:
                inflearn_posts.append({
                    'title': title,
                    'body': body
                })

        soup_posts = []
        study_items = soup_soup.find_all(class_='css-1089e3a')
        for item in study_items[:5]:
            content = item.get_text()
            soup_posts.append({
                'content': content
            })

        return inflearn_posts, soup_posts

projectapp/templates/projectapp/create.html
{% extends 'base.html' %}

{% block content %}

<div style="max-width: 500px; margin: auto;">
  <h4 style="margin-bottom: 1rem;">갤러리 생성</h4>
  <form action="{% url 'projectapp:create' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-group">
      <label for="title" style="margin-bottom: 0.5rem;">제목</label>
      <input type="text" name="title" id="title" style="display: block; width: 100%; padding: 0.375rem 0.75rem; font-size: 1rem; line-height: 1.5; color: #495057; background-color: #fff; border: 1px solid #ced4da; border-radius: 0.25rem;" required>
      <div style="color: #dc3545; margin-top: 0.25rem; font-size: 80%;">갤러리 제목을 입력하세요!</div>
    </div>
    <div class="form-group">
      <label for="image" style="margin-bottom: 0.5rem;">이미지</label>
      <input type="file" name="image" id="image" style="display: block; width: 100%; padding: 0.375rem 0.75rem; font-size: 1rem; line-height: 1.5; color: #495057; background-color: #fff; border: 1px solid #ced4da; border-radius: 0.25rem;" required>
      <div style="color: #dc3545; margin-top: 0.25rem; font-size: 80%;">예쁜 이미지를 넣어주세요!</div>
    </div>
    <div class="form-group">
      <label for="description" style="margin-bottom: 0.5rem;">설명</label>
      <textarea name="description" id="description" rows="5" style="display: block; width: 100%; padding: 0.375rem 0.75rem; font-size: 1rem; line-height: 1.5; color: #495057; background-color: #fff; border: 1px solid #ced4da; border-radius: 0.25rem;" required></textarea>
      <div style="color: #dc3545; margin-top: 0.25rem; font-size: 80%;">갤러리 소개글을 입력하세요!</div>
    </div>
    <input type="submit" value="갤러리 생성" style="display: block; width: 100%; padding: 0.375rem 0.75rem;
    font-size: 1rem; font-weight: 400; line-height: 1.5; color: #fff; background-color: #343a40;
    border: 1px solid #343a40; border-radius: 0.25rem; cursor: pointer; margin-top:1rem;">
  </form>
</div>
{% endblock %}

projectapp/templates/projectapp/delete.html
{% extends 'base.html' %}
{% block content %}
    <div style="text-align: center; max-width: 500px; margin: 4rem auto;">
        <div class="mb-4">
            <h2>카테고리 삭제:{{ target_project.title }}</h2>
        </div>
        <form action ="{% url 'projectapp:delete' pk=target_project.pk %}" method="POST">
            {% csrf_token %}
            <input type="submit" class="btn btn-danger col-4 mt-3">
        </form>
    </div
    >{% endblock %}

projectapp/templates/projectapp/detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


      <div>
        <div style="text-align: center; max-width:500px; margin: 4rem auto 1.5rem auto;">
            <img src="{{ target_project.image.url }}" alt="" style="height: 12rem; width:12rem; margin-bottom: 2rem; object-fit:cover">
            <h2>{{ target_project.title }}</h2>
            <h5 style="margin-bottom:3rem;">{{ target_project.description }}</h5>
        </div>
        <div class="text-center mb-5">
            {% if user.is_authenticated %}
                {% if not subscription %}
                    <a href="{% url 'subscribeapp:subscribe' %}?project_pk={{ target_project.pk }}" class="btn btn-primary">
                        구독
                    </a>
                {% else %}
                    <a href="{% url 'subscribeapp:subscribe' %}?project_pk={{ target_project.pk }}" class="btn btn-danger">
                        구독취소
                    </a>
                {% endif %}
            {% endif %}
        </div>

    {% if project_list %}
    <div class="container">
        <div class="row">
            {% for project in project_list %}
            <div class="col-3"> <!--4열 -->
                <a href="{% url 'projectapp:detail' pk=project.pk %}">
                    <div class="circle-card shadow">
                        <div class="circle-img-wrapper">
                            <img src="{{ project.image.url }}" class="card-img-top" alt="">
                        </div>
                    </div>
                </a>
            </div>
            {% if forloop.counter|divisibleby:4 %} <!-- 추가: 4열마다 줄 바꿈 -->
        </div><div class="row">
            {% endif %}
            {% endfor %}
        </div>
    </div>

    {% endif %}

    <hr> <!-- 구분 선 -->

    <div class="row">
        <div class="col-9">
            {% if article_list %}
            <div class="container">
                <div class="row row-cols-1 row-cols-md-3 g-4">
                    {% for article in article_list|slice:":12" %}
                    <div class="col">
                        <div class="card shadow">
                            <a href="{% url 'articleapp:detail' pk=article.pk %}">
                                <div class="card-body">
                                    <h5 class="card-title" style="font-size: 16px;">{{ article.title }}</h5>
                                    <div class="d-flex align-items-center">
                                        <a href="{% url 'likeapp:article_like' pk=article.pk %}">
                                            <i class="material-icons {% if article.like > 0 %}text-danger{% endif %}" style="color: {% if article.like == 0 %}var(--color-black);{% else %}var(--color-pink);{% endif %}">
                                                favorite
                                            </i>
                                        </a>
                                        <span class="ms-1" style="font-size: 12px;">{{ article.like }}</span>
                                    </div>
                                    <div class="d-flex align-items-center">
                                        <img src="{{ article.writer.profile.image.url }}" class="project-image" alt="{{ article.writer.profile.nickname }}">
                                        <span class="ms-1" style="font-size: 12px;">{{ article.writer.profile.nickname }}</span>
                                    </div>
                                    <div class="card-text">
                                        <h6 class="hits" style="font-size: 12px;">🖱조회수: {{ article.hits }}</h6>
                                        <div style="font-size: 12px;">{{ article.created_at }}</div>
                                    </div>
                                </div>
                            </a>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
            {% else %}
            <div class="text-center">
                <h1>게시글이 존재하지 않습니다.</h1>
            </div>
            {% endif %}
            <div class="text-center mt-3">
                <a href="{% url 'articleapp:create' %}" class="btn btn-primary col-12" style="font-size: 14px;">
                    글쓰기
                </a>
            </div>
        </div>
        <div class="col-3">
            <h6 style="text-align: center;">인프런과 스프의 {{ target_project.title }} 최근 글</h6>
            <table style="width: 80%; float: right;">
                <thead>
                    <tr>
                        {% if inflearn_posts or soup_posts %}
                        {% if inflearn_posts %}
                        {% endif %}
                        {% if soup_posts %}
                        {% endif %}
                        {% endif %}
                    </tr>
                </thead>
                <tbody>
                    {% for post in inflearn_posts %}
                    <tr>
                        <td><a href="https://www.inflearn.com/community/studies?status=unrecruited&order=recent">{{ post.title }}</a></td>
                    </tr>
                    {% endfor %}
                    {% for post in soup_posts %}
                    <tr>
                        <td><a href="https://soup.pw/projects">{{ post.content }}</a></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

    <style>
        .circle-card {
            width: 100px;
            height: 100px;
            border-radius: 50%;
            overflow: hidden;
        }

        .circle-img-wrapper {
            width: 100%;
            height: 100%;
            display: flex;
            justify-content: center;
            align-items: center;
        }

        .project-image {
            width: 20px;
            height: 20px;
        }
    </style>
{% endblock %}

projectapp/templates/projectapp/list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

   {% if project_list %}
    <div class="container">
        <div class="row">
            {% for project in project_list %}
                <div class="col-3"> <!--4열 -->
                    <a href="{% url 'projectapp:detail' pk=project.pk %}">
                        <div class="circle-card shadow">
                            <div class="circle-img-wrapper">
                                <img src="{{ project.image.url }}" class="card-img-top" alt="">
                            </div>
                        </div>
                    </a>
                </div>
                {% if forloop.counter|divisibleby:4 %} <!-- 추가: 4열마다 줄 바꿈 -->
                    </div><div class="row">
                {% endif %}
            {% endfor %}
        </div>
    </div>
{% else %}
    <div class="text-center">
        <h2>갤러리가 없습니다.</h2>
    </div>
{% endif %}

    <hr> <!-- 구분 선 -->

    {% if article_list %}
        <div class="container">
            <div class="row row-cols-1 row-cols-md-3 g-4">
                {% for article in article_list|slice:":12" %}  <!-- article_list를 12개로 제한 -->
                            <div class="col">
            <div class="card shadow">
                <a href="{% url 'articleapp:detail' pk=article.pk %}">
                    <div class="card-body">
                        <h5 class="card-title">{{ article.title }}</h5>
                        <div class="d-flex align-items-center">
                            <a href="{% url 'likeapp:article_like' pk=article.pk %}">
                                <i class="material-icons {% if article.like > 0 %}text-danger{% endif %}" style="color: {% if article.like == 0 %}var(--color-black);{% else %}var(--color-pink);{% endif %}">
                                    favorite
                                </i>
                            </a>
                            <span class="ms-1">{{ article.like }}</span>
                        </div>
                        <div class="card-text">
                            <div class="mb-2">{{ article.writer.profile.nickname }}</div>
                            <h6 class="hits">🖱조회수: {{ article.hits }}</h6>
                            <div>{{ article.created_at }}</div>
                        </div>
                        <img src="{{ article.project.image.url }}" class="project-image" alt="">
                    </div>
                </a>
            </div>
        </div>
        {% endfor %}
    </div>
    {% else %}
    <div class="text-center">
        <h1>게시글이 존재하지 않습니다.</h1>
    </div>
    {% endif %}



    <div class="text-center mt-3">
        <a href="{% url 'articleapp:create' %}" class="btn btn-primary col-3">
            글쓰기
        </a>
    </div>

    <style>
        .circle-card {
            width: 100px;
            height: 100px;
            border-radius: 50%;
            overflow: hidden;
        }

        .circle-img-wrapper {
            width: 100%;
            height: 100%;
            display: flex;
            justify-content: center;
            align-items: center;
        }

        .project-image {
            width: 20px;
            height: 20px;
        }
    </style>
{% endblock %}