accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accountapp.views import AccountDetailView, AccountCreateView, AccountUpdateView, AccountDeleteView

app_name = "accountapp"

urlpatterns = [
    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('create/', AccountCreateView.as_view(), name='create'),
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),
]

articleapp/urls.py
from django.urls import path
from django.views.generic import TemplateView

from articleapp.views import ArticleCreateView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView, ArticleListView

app_name = 'articleapp'
urlpatterns =[
    path('list/', ArticleListView.as_view(template_name='articleapp/list.html'), name='list'),
    path('create/', ArticleCreateView.as_view(), name='create'),
    path('detail/<int:pk>', ArticleDetailView.as_view(), name='detail'),
    path('update/<int:pk>', ArticleUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', ArticleDeleteView.as_view(), name='delete'),
    path('articles/list/<str:category_name>/', ArticleListView.as_view(), name='list'),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from articleapp.views import ArticleListView

urlpatterns = [
    path('', ArticleListView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls')),
    path('projects/', include('projectapp.urls')),
    path('subscribe/', include('subscribeapp.urls')),
    path('likes/', include('likeapp.urls')),
    path('accounts/', include('allauth.urls')),
    path('plus/', include('plusdefapp.urls')),
    path('chatgptcode/', include('chatgptcodeapp.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('jjit/', include('jjit.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

jjit/urls.py
#awesite/jjit/urls.py

from django.urls import path
from . import views

app_name = 'jjit' # 앱 이름 정의

urlpatterns = [
    path('', views.index, name='index'), # 'index'라는 이름으로 URL 패턴에 이름 부여
    path('<int:question_id>/', views.detail, name='detail'), # 'detail'이라는 이름으로 URL 패턴에 이름 부여
    path('<int:question_id>/answer/create/', views.answer_create, name='answer_create'),
    path('question/create/', views.question_create, name='question_create'),#질문 추가 버튼
    path('question/modify/<int:question_id>/', views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', views.question_delete, name='question_delete'),
    path('answer/modify/<int:answer_id>/', views.answer_modify, name='answer_modify'),


    # 'answer_create'라는 이름으로 URL 패턴에 이름 부여,#93
]

plusdefapp/urls.py
from django.urls import path


from plusdefapp.views import hello_world, chatgptcb, index, DeleteHistory

app_name = "plusdefapp"

urlpatterns = [
    path('hello_world/', hello_world, name='hello_world'),
    path('chatgptcb/', chatgptcb, name="chatgptcb"),
    path("chatqptbot/", index, name='main'),
    path("delete/", DeleteHistory, name='deleteChat'),
]

projectapp/urls.py
from django.urls import path

from projectapp.views import ProjectCreateView, ProjectDetailView, ProjectListView

app_name = 'projectapp'

urlpatterns = [
    path('list/',ProjectListView.as_view(), name='list'),
    path('create/', ProjectCreateView.as_view(), name='create'),
    path('detail/<int:pk>', ProjectDetailView.as_view(), name='detail'),

]

templates/base.html
<!DOCTYPE html>
<html lang="ko">
{% include 'head.html' %}

<body>
{% include 'navbar.html' %}

    {% include 'header.html' %}

    {% for message in messages %}
        <div class="text-center">
        <div class="btn btn-{{ message.tags }} px-3 my-3">
            {{ message }}

        </div>
    </div>

    {% endfor %}
    {% block content %}
    {% endblock %}

    {% include 'footer.html' %}
</body>
</html>

templates/footer.html
<div class="JJIT_footer">
    <div class="JJIT_footer_button">

    </div>
    <div style="margin-top:1rem;">

    </div>
    </div>

templates/head.html
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load static %}
    {% load bootstrap4 %}

    <!-- 부트스트랩 링크 -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>

    <!-- 구글 폰트 -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Permanent+Marker&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Material+Icons" rel="stylesheet">

    <!-- base.css -->
    <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">
</head>

templates/header.html
<div style=""class="JJIT_header">
    <nav>
        <div class="header_topic_navbar">
            <a href="{% url 'projectapp:list' %}" class="header_topic">
                <span>Study</span>
            </a>
            <a href="{% url 'articleapp:list' %}" class="header_topic">
                <span>Projects</span>
            </a>
            <a href="{% url 'jjit:index' %}" class="header_topic">
                <span>Community</span>
            </a>
        </div>

        <div>
            {% if not user.is_authenticated %}
            <a href="{% url 'accountapp:login' %}?next={{ request.path }}" class="header_topic">
                <span>Login</span>
            </a>

            <a href="{% url 'accountapp:create' %}" class="header_topic">
                <span>Join</span>
            </a>

            {% else %}

            <a href="{% url 'plusdefapp:main' %}" class="header_topic">
                <span>GPT ChatBot</span>
            </a>
            <a href="{% url 'chatgptcodeapp:main' %}" class="header_topic">
                <span>GPT코드</span>
            </a>
            <a href="{% url 'accountapp:detail' pk=user.pk %}" class="header_topic">
                <span>Profile</span>
            </a>
            <a href="{% url 'accountapp:logout' %}?next={{ request.path }}" class="header_topic">
                <span>Sign out</span>
            </a>
            {% endif %}
        </div>
    </nav>
</div>

templates/navbar.html
{% load bootstrap4 %}


<!-- 네비게이션바 -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'articleapp:list' %}">Jjit</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
      aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accountapp:logout' %}">로그아웃</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accountapp:update' user.pk %}">{{ user.username }} (정보수정)</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accountapp:login' %}">로그인</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accountapp:create' %}">회원가입</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>