articleapp/urls.py
from django.urls import path
from django.views.generic import TemplateView

from articleapp.views import ArticleCreateView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView, ArticleListView

app_name = 'articleapp'
urlpatterns =[
    path('list/', ArticleListView.as_view(template_name='articleapp/list.html'), name='list'),
    path('create/', ArticleCreateView.as_view(), name='create'),
    path('detail/<int:pk>', ArticleDetailView.as_view(), name='detail'),
    path('update/<int:pk>', ArticleUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', ArticleDeleteView.as_view(), name='delete'),
    path('articles/list/<str:category_name>/', ArticleListView.as_view(), name='list'),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from articleapp.views import ArticleListView

urlpatterns = [
    path('', ArticleListView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls')),
    path('projects/', include('projectapp.urls')),
    path('subscribe/', include('subscribeapp.urls')),
    path('likes/', include('likeapp.urls')),
    path('accounts/', include('allauth.urls')),
    path('plus/', include('plusdefapp.urls')),
    path('chatgptcode/', include('chatgptcodeapp.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('jjit/', include('jjit.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

jjit/urls.py
#awesite/jjit/urls.py

from django.urls import path
from . import views

app_name = 'jjit' # 앱 이름 정의

urlpatterns = [
    path('', views.index, name='index'), # 'index'라는 이름으로 URL 패턴에 이름 부여
    path('<int:question_id>/', views.detail, name='detail'), # 'detail'이라는 이름으로 URL 패턴에 이름 부여
    path('<int:question_id>/answer/create/', views.answer_create, name='answer_create'),
    path('question/create/', views.question_create, name='question_create'),#질문 추가 버튼
    path('question/modify/<int:question_id>/', views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', views.question_delete, name='question_delete'),
    path('answer/modify/<int:answer_id>/', views.answer_modify, name='answer_modify'),


    # 'answer_create'라는 이름으로 URL 패턴에 이름 부여,#93
]

likeapp/urls.py
from django.urls import path

from likeapp.views import LikeArticleView

app_name='likeapp'

urlpatterns = [
    path('article/like/<int:pk>', LikeArticleView.as_view(), name='article_like'),
]

articleapp/models.py
from django.contrib.auth.models import User
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField
from projectapp.models import Project
from django.urls import reverse


class Article(models.Model):
    writer = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='article', null=True)
    project = models.ForeignKey(Project, on_delete=models.SET_NULL, related_name='article', null=True)
    category = models.ForeignKey('Category', on_delete=models.SET_NULL, related_name='article', null=True)  # 수정된 부분
    title = models.CharField(max_length=200, null=True)
    content = RichTextUploadingField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    like = models.IntegerField(default=0)
    hits = models.PositiveIntegerField(default=1, verbose_name='조회수')


class Category(models.Model):
    name = models.CharField(max_length=20, unique=True)
    description = models.CharField(max_length=200, null=True, blank=True)
    has_answer = models.BooleanField(default=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('article:list', kwargs={'category_name': self.name})  # 수정된 부분

articleapp/forms.py
from ckeditor.widgets import CKEditorWidget
from django import forms
from articleapp.models import Article
from projectapp.models import Project

class ArticleCreationForm(forms.ModelForm):
    content = forms.CharField(widget=CKEditorWidget())
    project = forms.ModelChoiceField(queryset=Project.objects.all(), required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['category'].widget.attrs['class'] = 'form-control'

    class Meta:
        model = Article
        fields = ['title', 'project', 'content', 'category']

articleapp/views.py
from datetime import datetime, timedelta
from django.http import HttpResponse
from django.db.models import Q, F
from django.contrib.auth.decorators import login_required
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView, ListView
from django.views.generic.edit import FormMixin
from articleapp.decorators import article_ownership_required
from articleapp.forms import ArticleCreationForm
from commentapp.forms import CommentCreationForm
from django.utils import timezone
from django import forms
from django.shortcuts import get_object_or_404
from .models import Article, Category


# Create your views here.

@method_decorator(login_required, 'get')
@method_decorator(login_required, 'post')
class ArticleCreateView(CreateView):
    model = Article
    form_class = ArticleCreationForm
    template_name = 'articleapp/create.html'

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.fields['category'] = forms.ModelChoiceField(queryset=Category.objects.all())
        return form

    def form_valid(self, form):
        article = form.save(commit=False)
        article.writer = self.request.user
        article.created_at = timezone.now()
        article.category = form.cleaned_data['category']
        article.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('articleapp:detail', kwargs={'pk': self.object.pk})




class ArticleDetailView(DetailView, FormMixin):
    model = Article
    form_class = CommentCreationForm
    context_object_name = 'target_article'
    template_name = 'articleapp/detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['created_at'] = self.object.created_at

        id = self.object.pk
        response = super().render_to_response(context)
        expire_date, now = datetime.now(), datetime.now()
        expire_date += timedelta(days=1)
        expire_date = expire_date.replace(hour=0, minute=0, second=0, microsecond=0)
        expire_date -= now
        max_age = expire_date.total_seconds()

        cookie_value = self.request.COOKIES.get('hitblog', '_')

        if f'_{id}_' not in cookie_value:
            cookie_value += f'{id}_'
            response.set_cookie('hitblog', value=cookie_value, max_age=max_age, httponly=True)
            article = self.get_object()
            article.hits = F('hits') + 1
            article.save()

        return context


@method_decorator(article_ownership_required, 'get')
@method_decorator(article_ownership_required, 'post')
class ArticleUpdateView(UpdateView):
    model = Article
    context_object_name = 'target_article'
    form_class = ArticleCreationForm
    template_name = 'articleapp/update.html'

    def get_success_url(self):
        return reverse('articleapp:detail', kwargs={'pk': self.object.pk})


@method_decorator(article_ownership_required, 'get')
@method_decorator(article_ownership_required, 'post')
class ArticleDeleteView(DeleteView):
    model = Article
    context_object_name = 'target_article'
    success_url = reverse_lazy('articleapp:list')
    template_name = 'articleapp/delete.html'




class ArticleListView(ListView):
    model = Article
    context_object_name = 'article_list'
    template_name = 'articleapp/list.html'
    paginate_by = 12

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['created_at_list'] = [article.created_at for article in context['article_list']]
        context['hits_list'] = [article.hits for article in context['article_list']]
        context['category_list'] = Category.objects.all()
        category_name = self.kwargs.get('category_name')
        if category_name:
            category = get_object_or_404(Category, name=category_name)
            context['category'] = category
            context['category_description'] = category.description
        return context

    def get_queryset(self):
        article_list = super().get_queryset()
        kw = self.request.GET.get('kw', '')

        # 정렬 옵션 가져오기
        sort_by = self.request.GET.get('sort_by', '-created_at')

        category_name = self.kwargs.get('category_name', '스터디')
        if category_name == '스터디':
            # 기본 카테고리인 경우 모든 글을 가져옴
            if kw:
                article_list = article_list.filter(
                    Q(title__icontains=kw) |
                    Q(content__icontains=kw)
                ).distinct()
        else:
            # 특정 카테고리인 경우 해당 카테고리의 글만 가져옴
            category = get_object_or_404(Category, name=category_name)
            if kw:
                article_list = article_list.filter(
                    Q(title__icontains=kw) |
                    Q(content__icontains=kw),
                    category=category
                ).distinct()
            else:
                article_list = article_list.filter(category=category)

        # 정렬 기능 추가
        if sort_by == 'like':
            article_list = article_list.order_by('-like')
        elif sort_by == 'hits':
            article_list = article_list.order_by('hits')
        else:
            article_list = article_list.order_by(sort_by)

        return article_list

articleapp/templates/articleapp/create.html
 {% load bootstrap4 %}
{% block content %}



   <script src="https://code.jquery.com/jquery-3.5.1.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

    <script src="//cdn.ckeditor.com/4.19.0/full/ckeditor.js"></script>


    <style>
        body {
            background-color: rgb(17 24 39);
        }
        .card-body {
            background-color: rgb(31, 41, 55);
        }
        .card-title,
        label,
        textarea {
            color: white;
        }
    </style>

<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title text-center mb-6" style="font-weight: bold;">게시글 쓰기</h4>
                    <form action="{% url 'articleapp:create' %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}

                        <div class="form-group mt-4">
                            <label for="{{ form.title.id_for_label }}">제목</label>
                            <input type="text" class="form-control" id="{{ form.title.id_for_label }}" name="{{ form.title.html_name }}" required>
                        </div>

                        <div class="form-group mt-4">
    <label for="{{ form.category.id_for_label }}">카테고리</label>
    <select class="form-control" id="{{ form.category.id_for_label }}" name="{{ form.category.html_name }}" required>
        {% for category in form.category.field.queryset %}
            <option value="{{ category.pk }}">{{ category.name }}</option>
        {% endfor %}
    </select>
</div>

                        <div class="form-group mt-4">
                            <label for="{{ form.project.id_for_label }}">분야</label>
                            <select class="form-control" id="{{ form.project.id_for_label }}" name="{{ form.project.html_name }}" required>
                                {% for project in form.project.field.queryset %}
                                    <option value="{{ project.pk }}">{{ project.title }}</option>
                                {% endfor %}
                            </select>
                        </div>

                        <div class="form-group mt-4">
                            <label for="{{ form.content.id_for_label }}">내용</label>
                            <textarea class="ckeditor form-control" id="{{ form.content.id_for_label }}" name="{{ form.content.html_name }}" required rows="6"></textarea>
                        </div>

                        <div class="text-center">
                            <button type="submit" class="btn btn-dark rounded-pill col-md-6 mt-3">작성 완료</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>


    <script>
    CKEDITOR.replace("{{ form.content.id_for_label }}", {
        toolbar: [
             { name: 'document', items: ['NumberedList', 'BulletedList', 'Outdent', 'Indent', 'Blockquote'] },
                { name: 'styles', items: ['JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock'] },
                { name: 'links', items: ['Link', 'Unlink', 'Anchor'] },
                { name: 'insert', items: ['Image', 'Flash', 'Table', 'HorizontalRule'] },
                '/',
                { name: 'basicstyles', items: ['Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript'] },
                { name: 'styles', items: ['Format', 'Font', 'FontSize'] }, // 스타일, 문단, 글꼴 크기 기능 추가
                { name: 'colors', items: ['TextColor', 'BGColor'] },
                { name: 'undo', items: ['Undo', 'Redo'] },
                { name: 'tools', items: ['Maximize'] }
        ],
    });

    </script>

{% endblock %}

articleapp/templates/articleapp/delete.html
{% extends 'base.html' %}
{% block content %}
    <div style="text-align: center; max-width: 500px; margin: 4rem auto;">
        <div class="mb-4">
            <h2>게시글 삭제:{{ target_article.title }}</h2>
        </div>
        <form action ="{% url 'articleapp:delete' pk=target_article.pk %}" method="POST">
            {% csrf_token %}
            <input type="submit" class="btn btn-danger col-4 mt-3">
        </form>
    </div
    >{% endblock %}

articleapp/templates/articleapp/detail.html
{% extends 'base.html' %}

{% block content %}


    <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.js"></script>

  <div>
    <div style="text-align: center; max-width: 700px; margin: 4rem auto;">
        <h1 style="font-weight: bold;">
            {{ target_article.title }}
        </h1>
        <div style="height:2rem;">
            <a href="{% url 'likeapp:article_like' pk=target_article.pk %}">
                <i style="vertical-align: middle; font-size:1.2rem; color: #f77" class="material-icons">
                    favorite
                </i>
            </a>
            <span style="vertical-align: middle; font-size:1.2rem;">
                {{target_article.like}}
            </span>

        </div>
        <h3>
            {{ target_article.writer.profile.nickname }}
        </h3>
        <div>
            {{ target_article.created_at }}
        </div>

<h5 class="hits">🖱조회수 : {{ target_article.hits }}</h5>
    <hr>
    <div class="card-text" style="white-space: pre-line; text-align: left; margin-left: auto; margin-right: auto; max-width: 600px; background-color: rgb(31, 41, 55);">
            {% autoescape off %}
            {{ target_article.content|safe }}
            {% endautoescape %}
        </div>
        <hr>
        {% if target_article.writer == user %}
            <a href="{% url 'articleapp:update' pk=target_article.pk %}" class="btn btn-success col-3">
                게시글 수정
            </a>
            <a href="{% url 'articleapp:delete' pk=target_article.pk %}" class="btn btn-success col-3">
                게시글 삭제
            </a>
        {% endif %}
        <hr>
        {% for comment in target_article.comment.all %}
        {% include 'commentapp/detail.html' with comment=comment %}
        {% endfor %}
        {% include 'commentapp/create.html' with article=target_article %}
    </div>
</div>


{% endblock %}

articleapp/templates/articleapp/list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container my-3">
    <div class="row justify-content-center">
        <div class="col-sm-5 col-md-1 col-lg-2 p-2">

      <!-- Sidebar -->
<nav id="sidebar" class="border-top border-secondary">
    <div class="list-group justify-content-center">
        {% for cat in category_list|dictsort:'name' %}
            {% if cat == category %}
                <a class="rounded-0 list-group-item list-group-item-action list-group-item-light text-black text-center" style="background-color: #9ca3af ;" href="{% url 'articleapp:list' cat.name %}">{{ cat.name }}</a>
            {% else %}
                <a class="rounded-0 list-group-item list-group-item-action list-group-item-light text-black text-center" style="background-color: #9ca3af ;" href="{% url 'articleapp:list' cat.name %}">{{ cat.name }}</a>
            {% endif %}
        {% endfor %}
    </div>
</nav>

</div>



        <div class="col-sm-12 col-md-9 col-lg-10 p-2">
            <!-- Content -->
            <div id="content" class="border-top border-secondary">
                <div class="content_block">
                    <h5 class="border-bottom pl-2 pb-3 my-2">{{ category.description }}</h5>
                    <div class="row justify-content-between my-3">

                        <!-- 검색창 -->
                        <div class="search-bar my-3" style="max-width: 350px; margin-left: auto;">
                            <div class="d-flex justify-content-end mb-3">
                                <input type="text" id="search_kw" class="form-control" placeholder="제목 또는 내용으로 검색" value="{{ kw|default_if_none:'' }}">
                                <div class="input-group">
                                    <button class="btn btn-primary" type="button" id="btn_search">검색</button>
                                </div>
                            </div>
                        </div>

                        <!-- 정렬바 -->
                        <div class="row mb-3">
                            <div class="col">
                                <label for="sort"></label>
                                <div class="btn-group">
                                    <button type="button" class="btn btn-primary" value="-hits" onclick="handleSortChange(this.value)">
                                        <i class="bi bi-bar-chart-line"></i> 조회수
                                    </button>
                                    <button type="button" class="btn btn-primary" value="like" onclick="handleSortChange(this.value)">
                                        <i class="bi bi-heart"></i> 좋아요
                                    </button>
                                    <button type="button" class="btn btn-primary" value="created_at" onclick="handleSortChange(this.value)">
                                        <i class="bi bi-clock"></i> 오래된 순
                                    </button>
                                </div>
                            </div>
                        </div>
{% if article_list %}
<!-- 게시글 목록 -->
<div class="row row-cols-1 row-cols-md-4 g-4">
    {% for article in article_list %}
    <div class="col">
        <div class="card shadow">
            <a href="{% url 'articleapp:detail' pk=article.pk %}">
                <div class="card-body">
                    <h5 class="card-title">{{ article.title }}</h5>
                    <div class="d-flex align-items-center">
                        <a href="{% url 'likeapp:article_like' pk=article.pk %}">
                            <i class="material-icons {% if article.like > 0 %}text-danger{% endif %}" style="color: {% if article.like == 0 %}var(--color-black);{% else %}var(--color-pink);{% endif %}">
                                favorite
                            </i>
                        </a>
                        <span class="ms-1">{{ article.like }}</span>
                    </div>
                    <div class="card-text">
                        <div class="mb-2" style="font-size: 12px;">{{ article.writer.profile.nickname }}</div>
                        <h6 class="hits" style="font-size: 10px;">🖱조회수: {{ article.hits }}</h6>
                        <div style="font-size: 10px;">{{ article.created_at }}</div>
                    </div>
                    <img src="{{ article.project.image.url }}" class="project-image" alt="">
                </div>
            </a>
        </div>
    </div>
    {% endfor %}
</div>
{% else %}
<div class="text-center">
    <h1>게시글이 존재하지 않습니다.</h1>
</div>
{% endif %}


{% include 'snippets/pagination.html' with page_obj=page_obj %}

<div class="text-center mt-3">
    <a href="{% url 'articleapp:create' %}" class="btn btn-primary col-3">
        글쓰기
    </a>
</div>

<form id="searchForm" method="get" action="{% url 'articleapp:list' %}">
    <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
    <input type="hidden" id="page" name="page" value="{{ page }}">
</form>

<style>
    .project-image {
        width: 20px;
        height: 20px;
    }
</style>

<script>
    // 정렬 기능
    function handleSortChange(sortBy) {
        const url = new URL(window.location.href);
        url.searchParams.set('sort_by', sortBy);
        window.location.href = url;
    }

    // 선택한 정렬 기준을 유지하기 위해 드롭다운 메뉴 초기화
    const sortSelect = document.getElementById('sort');
    const sortByParam = new URLSearchParams(window.location.search).get('sort_by');
    sortSelect.value = sortByParam;
</script>
{% endblock %}

{% block script %}

<script type='text/javascript'>
    const page_elements = document.getElementsByClassName("page-link");
    Array.from(page_elements).forEach(function (element) {
        element.addEventListener('keydown', function (event) {
            document.getElementById('page').value = this.dataset.page;
            document.getElementById('searchForm').submit();
        });
    });
    const btn_search = document.getElementById("btn_search");
    btn_search.addEventListener('keydown', function (event) {
        document.getElementById('kw').value = document.getElementById('search_kw').value;
        document.getElementById('page').value = 1;
        document.getElementById('searchForm').submit();
    });
</script>
{% endblock %}

articleapp/templates/articleapp/update.html
{% load bootstrap4 %}
{% block content %}

   <script src="https://code.jquery.com/jquery-3.5.1.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

    <script src="//cdn.ckeditor.com/4.19.0/full/ckeditor.js"></script>


    <style>
        body {
            background-color: rgb(17 24 39);
        }
        .card-body {
            background-color: rgb(31, 41, 55);
        }
        .card-title,
        label,
        textarea {
            color: white;
        }
    </style>

    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title text-center mb-6" style="font-weight: bold;">게시글 수정</h4>
                        <form action="{% url 'articleapp:create' %}" method="post" enctype="multipart/form-data">
                            {% csrf_token %}

                            <div class="form-group mt-4">
                                <label for="{{ form.title.id_for_label }}">제목</label>
                                <input type="text" class="form-control" id="{{ form.title.id_for_label }}" name="{{ form.title.html_name }}" required>
                            </div>

                            <div class="form-group mt-4">
                                <label for="{{ form.project.id_for_label }}">프로젝트</label>
                                <select class="form-control" id="{{ form.project.id_for_label }}" name="{{ form.project.html_name }}" required>
                                    {% for project in form.project.field.queryset %}
                                        <option value="{{ project.pk }}">{{ project.title }}</option>
                                    {% endfor %}
                                </select>
                            </div>

                            <div class="form-group mt-4">
                                <label for="{{ form.content.id_for_label }}">내용</label>
                                <textarea class="ckeditor form-control" id="{{ form.content.id_for_label }}" name="{{ form.content.html_name }}" required rows="6"></textarea>
                            </div>

                            <div class="text-center">
                                <button type="submit" class="btn btn-dark rounded-pill col-md-6 mt-3">작성 완료</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <script>
    CKEDITOR.replace("{{ form.content.id_for_label }}", {
        toolbar: [
             { name: 'document', items: ['NumberedList', 'BulletedList', 'Outdent', 'Indent', 'Blockquote'] },
                { name: 'styles', items: ['JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock'] },
                { name: 'links', items: ['Link', 'Unlink', 'Anchor'] },
                { name: 'insert', items: ['Image', 'Flash', 'Table', 'HorizontalRule'] },
                '/',
                { name: 'basicstyles', items: ['Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript'] },
                { name: 'styles', items: ['Format', 'Font', 'FontSize'] }, // 스타일, 문단, 글꼴 크기 기능 추가
                { name: 'colors', items: ['TextColor', 'BGColor'] },
                { name: 'undo', items: ['Undo', 'Redo'] },
                { name: 'tools', items: ['Maximize'] }
        ],
    });

    </script>

{% endblock %}